sudo: required
services:
  - docker

before_install:
  - docker build -t edwardz10/docker-rect -f Dockerfile.dev .

script:
  - docker run edwardz10/docker-rect npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-759230159651"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secrey_access_key:
    secure: "$AWS_SECRET_KEY"

